class_name ArtDB
extends RefCounted
## Static texture lookup for res://art/<id>.svg. Cached; returns null when missing
## so callers fall back to primitive _draw.

static var _cache: Dictionary = {}

static func tex(id: String) -> Texture2D:
	if _cache.has(id):
		return _cache[id] as Texture2D
	var path: String = "res://art/%s.svg" % id
	var t: Texture2D = null
	if ResourceLoader.exists(path):
		t = load(path) as Texture2D
	_cache[id] = t
	return t

## Redesign art pass (REDESIGN_SPEC §4), generated by art/_gen_svg_redesign.py.
## Outpost buildings op_<id>_<1|2|3> are multi-tile: 64 px per footprint cell.
const REDESIGN_IDS: PackedStringArray = [
	"core_bastion", "core_locked", "core_open", "fx_cannon", "fx_slag", "fx_beam", "fx_pulse_ring", "fx_chain",
	"fx_splash", "fx_orbital", "fx_emp", "frost", "obelisk", "hut_infantry", "hut_sapper", "troop_rifleman",
	"troop_sapper", "troop_drone", "courier", "pk_arsenal", "pk_overclock", "pk_fort", "pk_ledger", "pk_optics",
	"pk_crit", "pk_logistics", "pk_core", "pk_barracks", "pk_gambit", "sp_orbital", "sp_emp", "sp_repair",
	"sp_overdrive", "sp_magnet", "sp_timewarp", "insight", "in_dmg", "in_hp", "in_cash", "in_rate", "in_luck",
	"in_drop", "in_crate", "card_common", "card_rare", "card_epic", "card_legendary", "card_insight", "tag_eco",
	"tag_dps", "tag_aoe", "tag_control", "tag_troop", "tag_special", "tag_sustain", "slot_frame", "slot_barrel",
	"slot_capacitor", "slot_engine", "slot_set", "slot_locked", "citadel_heart", "golden_ratio",
	"singularity_lens", "eye_of_storm", "brood_mother", "cur_coin", "cur_cash", "cur_scrap", "cur_shard",
	"tile_ash", "tile_rock", "tile_water", "op_conduit", "op_conduit_n", "op_conduit_s", "op_conduit_w",
	"op_conduit_e", "op_plug", "op_vein", "op_plot_locked", "op_builder", "op_timer", "op_relay_1",
	"op_relay_2", "op_relay_3", "op_mill_1", "op_mill_2", "op_mill_3", "op_refinery_1", "op_refinery_2",
	"op_refinery_3", "op_gemmine_1", "op_gemmine_2", "op_gemmine_3", "op_research_1", "op_research_2",
	"op_research_3", "op_barracks_1", "op_barracks_2", "op_barracks_3", "op_archive_1", "op_archive_2",
	"op_archive_3", "op_warehouse_1", "op_warehouse_2", "op_warehouse_3", "op_scrapyard_1", "op_scrapyard_2",
	"op_scrapyard_3", "op_beacon_1", "op_beacon_2", "op_beacon_3", "dc_smelter", "dc_crates", "dc_bookshelf",
	"dc_orrery", "dc_yard", "dc_dummy", "dc_lamp", "dc_brazier", "dc_tree", "dc_shrub", "dc_pond", "dc_banner",
	"dc_trophy", "rf_root", "rf_power", "rf_economy", "rf_mastery", "rf_node_locked", "rf_node_owned",
	"ui_hotkey_frame", "ui_cooldown", "ui_reroll", "ui_banish", "ui_collect", "ui_rotate", "ui_demolish",
	"ui_move", "ui_blueprint"
]

## Footprint (cells) of each Outpost building art id stem.
const OP_FOOTPRINT: Dictionary = {"relay": Vector2i(1, 1), "mill": Vector2i(2, 2), "refinery": Vector2i(2, 2), "gemmine": Vector2i(2, 2), "research": Vector2i(2, 2), "barracks": Vector2i(2, 2), "archive": Vector2i(1, 2), "warehouse": Vector2i(2, 1), "scrapyard": Vector2i(2, 2), "beacon": Vector2i(1, 1)}
